-- V1: 초기 스키마 (H2 PostgreSQL 호환 모드 + PostgreSQL 공용 SQL만)
-- DB 전용 구문(pg_trgm 등)은 db/migration/postgresql 에 둔다.

CREATE TABLE store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(200) NOT NULL,
    region VARCHAR(30) NOT NULL,
    category VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_store_name_address UNIQUE (name, address)
);

CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    nickname VARCHAR(20) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(5000) NOT NULL,
    rating INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_review_store FOREIGN KEY (store_id) REFERENCES store (id),
    CONSTRAINT ck_review_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_review_store ON review (store_id);
CREATE INDEX idx_review_created ON review (created_at);

CREATE TABLE comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    nickname VARCHAR(20) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    content VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_comment_review FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE
);

CREATE INDEX idx_comment_review ON comment (review_id);
